Create CONTRIBUTING.md
versotile-org/fortress pull request #2
Opened 2024-07-08 09:12 UTC by felsweg

2024-07-08 09:13 UTC, wusyong approved these changes

2024-07-08 12:23 UTC, Mikopet requested changes

2024-07-08 12:23 UTC, Mikopet commented on .github/CONTRIBUTING.md
> +Hello! We, the maintainers, are very pleased that you are interested in contributing to Verso. However, before you submit your contribution, please take a moment to read the [Code of Conduct](CODE_OF
Instead `Verso`, put `Fortress`.

2024-07-08 12:23 UTC, Mikopet commented on .github/CONTRIBUTING.md
> +Hello! We, the maintainers, are very pleased that you are interested in contributing to Verso. However, before you submit your contribution, please take a moment to read the [Code of Conduct](CODE_OF
link is also broken, no code of conduct file. (that could be copied from verso repo I guess.)

2024-08-02 06:22 UTC, tensor-programming approved these changes

2024-08-02 10:52 UTC, felsweg commented
@Mikopet may you kindly approve the changes? thank you

2024-08-02 14:57 UTC, Mikopet requested changes

2024-08-02 14:57 UTC, Mikopet commented on .github/CONTRIBUTING.md
> +Hello! We, the maintainers, are very pleased that you are interested in contributing to Verso. However, before you submit your contribution, please take a moment to read the [Code of Conduct](CODE_OF
```suggestion
Hello! We, the maintainers, are very pleased that you are interested in contributing to Fortress. However, before you submit your contribution, please take a moment to read the [Code of Conduct](CODE_OF_CONDUCT.md) and the appropriate section for the contribution you plan to make:
```

2024-08-02 14:57 UTC, Mikopet commented on .github/CONTRIBUTING.md
> +- Check if the issue is reproducible with the latest version of Verso. If you are using a nightly release, please indicate the specific version you are using.
```suggestion
- Check if the issue is reproducible with the latest version of Fortress. If you are using a nightly release, please indicate the specific version you are using.
```

2024-08-04 15:57 UTC, felsweg reviewed
accept requested changes

2024-08-06 11:09 UTC, tensor-programming approved these changes

2024-08-06 13:33 UTC, merged